/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/left.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.id_Punta.geometry} material={materials.Default} position={[-0.78, 0, -2.02]} rotation={[-Math.PI, 0.01, -Math.PI]} scale={[-6.59, 6.59, 6.59]} />
    </group>
  )
}

useGLTF.preload('/left.glb')
