/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 nike.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/nike.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_26.geometry} material={materials.Main} position={[-0.809, 0.675, 1.193]} rotation={[1.6, -0.914, 1.601]} scale={0.585} />
    </group>
  )
}

useGLTF.preload('/nike.glb')
